export const life_path = {
	background: {
		'1': 'Your family lost everything through betrayal.',
		'2': 'Your family lost everything through bad management',
		'3':
			'Your family was exiled or otherwise driven from their original home/nation/Corporation.',
		'4': 'Your family is imprisoned and you alone escaped.',
		'5': 'Your family vanished. You are the only remaining member.',
		'6': 'Your family was killed and you were the only survivor.',
		'7':
			'Your family is involved in a long–term conspiracy, organization, or association, such as a crime family or revolutionary group.',
		'8': 'Your family was scattered to the winds due to misfortune.',
		'9':
			'Your family is cursed with a hereditary feud that has lasted for generations.',
		'10':
			'You are the inheritor of a family debt; you must honor this debt before moving on with your life.',
	},
	motivation: {
		'1': 'Money',
		'2': 'Honor',
		'3': 'Your word',
		'4': 'Honesty',
		'5': 'Knowledge',
		'6': 'Vengeance',
		'7': 'Love',
		'8': 'Power',
		'9': 'Having a good time',
		'10': 'Friendship',
	},
	goals: {
		'1': 'Get rid of a bad reputation.',
		'2': 'Gain power and control.',
		'3': 'Get off the street no matter what it takes.',
		'4': 'Cause pain and suffering to anyone who crosses you.',
		'5': 'Live down your past life and try to forget it.',
		'6': 'Hunt down those responsible for your life and make them pay.',
		'7': 'Get what’s rightfully yours.',
		'8': 'Save, if possible, anyone else involved in your background.',
		'9': 'Gain fame and recognition.',
		'10': 'Become feared and respected.',
	},
	friends: {
		'1': 'Like an older sibling to you',
		'2': 'Like a younger sibling to you',
		'3': 'A teacher or mentor',
		'4': 'A partner or coworker',
		'5': 'A former lover',
		'6': 'An old enemy',
		'7': 'Like a parent to you',
		'8': 'An old childhood friend',
		'9': 'A relative',
		'10': 'Someone with a common interest',
	},
	enemies: {
		'1': 'Ex–friend',
		'2': 'Ex–lover',
		'3': 'Relative',
		'4': 'Childhood enemy',
		'5': 'Person working for you',
		'6': 'Person you work for',
		'7': 'Partner or coworker',
		'8': 'Booster gang member',
		'9': 'Corporate Exec',
		'10': 'Government official',
	},
	romance: {
		'1': 'Your lover died in an accident.',
		'2': 'Your lover mysteriously vanished.',
		'3': 'It just didn’t work out.',
		'4': 'A personal goal or vendetta came between you and your lover.',
		'5': 'Your lover was kidnapped.',
		'6': 'Your lover went insane.',
		'7': 'Your lover committed suicide.',
		'8': 'Your lover was killed in a fight.',
		'9': 'A rival cut you out of the action.',
		'10': 'Your lover is imprisoned or exiled.',
	},
	personality: {
		'1': 'Shy and secretive',
		'2': 'Rebellious, antisocial, violent',
		'3': 'Arrogant, proud and aloof',
		'4': 'Moody, rash and headstrong',
		'5': 'Picky, fussy, and nervous',
		'6': 'Stable and serious',
		'7': 'Silly and fluff–headed',
		'8': 'Sneaky and deceptive',
		'9': 'Intellectual and detached',
		'10': 'Friendly and outgoing',
	},
};
